# Meta Data for SEO

## Homepage
title = "Bitmask for OpenWRT"
titleSeparator = "-"
titleAddition = "Put RiseupVPN in your router"
description = "just that"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "leapcode"
twitterCreator = "leapcode"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/leapcode"
schemaGitHub = "https://github.com/kalikaneko/bitmask-openwrt"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by a text editor."

# Alert
alert = false
alertText = ""

# Edit Page
docsRepo = "https://github.com/kalikaneko/bitmask-openwrt-site"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  bootStrapJs = false
  breadCrumb = true 
  highLight = true
  kaTex = false
